default_agent: customer_support
agents:
  customer_support:
    name: customer_support
    entrypoint: customer_support.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::975800734221:role/AmazonBedrockAgentCoreExecutionRole
      execution_role_auto_create: false
      account: '975800734221'
      region: us-west-2
      ecr_repository: 975800734221.dkr.ecr.us-west-2.amazonaws.com/financial-email-processor
      ecr_auto_create: true
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: customer_support-vZmDFmAIuL
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:975800734221:runtime/customer_support-vZmDFmAIuL
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-customer_support-builder
      execution_role: arn:aws:iam::975800734221:role/AmazonBedrockAgentCoreSDKCodeBuild-us-west-2-68b3df88f9
      source_bucket: bedrock-agentcore-codebuild-sources-975800734221-us-west-2
    authorizer_configuration: null
    oauth_configuration: null
